[server]
port=5050

[mysql]
url="root:123456@tcp(localhost:3306)/brian"

[redis]
addr="localhost:6379"

[apollo]
enabled=true
appId="SampleApp"
cluster="DEV"
ip="http://localhost:8080"
namespaceName="application"

[xxlJob]
enabled=false
serverAddr="http://localhost:9090"
accessToken="default_token"
executorPort="9999"
registryKey="xxl-job-executor-sample"
logDir="/Users/sven/Downloads/xxl-job-log"
logRetention=7

[rocketMQ]
enabled=false
nameServer=["192.168.110.107:9876"]