[Server]
Port=5050

[MySQL.main]
Url="root:123456@tcp(localhost:3306)/brian"

[Redis.main]
Addr="localhost:6379"

[Apollo]
Enabled=true
AppId="SampleApp"
Cluster="DEV"
IP="http://localhost:8080"
NamespaceName="application"

[XxlJob]
Enabled=false
ServerAddr="http://localhost:9090"
AccessToken="default_token"
ExecutorPort="9999"
RegistryKey="xxl-job-executor-sample"
LogDir="/Users/sven/Downloads/xxl-job-log"
LogRetention=7

[RocketMQ.main]
Enabled=false
NameServer=["127.0.0.1:9876"]
GroupName="HereWeGo"
MessageModel=1
Retry=2